import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Home0011One</Link>
        </li>
        <li>
          <Link to="/home0011">Home0011</Link>
        </li>
        <li>
          <Link to="/home0012expandtwo">Home0012ExpandTwo</Link>
        </li>
        <li>
          <Link to="/home0012expandone">Home0012ExpandOne</Link>
        </li>
        <li>
          <Link to="/home0012expandfour">Home0012ExpandFour</Link>
        </li>
        <li>
          <Link to="/home0012expandsix">Home0012ExpandSix</Link>
        </li>
        <li>
          <Link to="/home0012expandthree">Home0012ExpandThree</Link>
        </li>
        <li>
          <Link to="/home0012expandfive">Home0012ExpandFive</Link>
        </li>
        <li>
          <Link to="/home0012expand">Home0012Expand</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
